# SPDX-FileCopyrightText: 2019 Free Software Foundation Europe e.V. <https://fsfe.org>
# SPDX-FileCopyrightText: 2022 Carmen Bianca Bakker <carmenbianca@fsfe.org>
# SPDX-FileCopyrightText: 2023 DB Systel GmbH
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Test suites

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      max-parallel: 10
      # do not abort the whole test job if one combination in the matrix fails
      fail-fast: false
      matrix:
        container:
          [
            "nikolaik/python-nodejs:python3.10-nodejs24",
            "nikolaik/python-nodejs:python3.14-nodejs24",
          ]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install poetry~=1.3.0
          poetry install --no-interaction --only main,test --all-extras
      - name: Run tests with pytest
        run: |
          poetry run pytest -vv --cov=reuse

  pylint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install poetry~=1.3.0
          poetry install --no-interaction --only main,dev,test
      - name: Lint with Pylint
        run: |
          poetry run pylint src/reuse/ tests/

  black:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install poetry~=1.3.0
          poetry install --no-interaction --only dev
      - name: Test formatting with black
        run: |
          poetry run isort --check src/ tests/
          poetry run black --check .

  mypy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install poetry~=1.3.0
          poetry install --no-interaction --only main,dev,test
      - name: Test typing with mypy
        run: |
          poetry run mypy

  prettier:
    runs-on: ubuntu-24.04
    container: node:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install prettier
        run: npm install prettier@3.0.3
      - name: Run prettier
        run: npx prettier --check .

  reuse:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install poetry~=1.3.0
          poetry install --no-interaction --only main
      - name: Test REUSE compliance
        run: make reuse

  docs:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install poetry~=1.3.0
          poetry install --no-interaction --only main,docs
      - name: Create docs with Sphinx
        run: |
          make docs
